apiVersion: v1
kind: Service
metadata:
  name: mcm-svc-registry-test
  namespace: multicluster-endpoint
spec:
  selector:
    component: mcm-svc-registry-dns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP